services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
